# ARGUMENTS - Define reusable variables for use across stages
ARG APP_PATH="/usr/application/"
ARG VENV_PATH="/opt/venv"
ARG UV_PATH="/root/.cargo/bin/uv"

# BASE IMAGE for package installation
FROM python:3.12-alpine as build
LABEL authors="jolivera"

# Import arguments in the build context
ARG APP_PATH
ARG VENV_PATH
ARG UV_PATH

# Install necessary OS packages
RUN apk add --no-cache build-base curl

# Set up the virtual environment
ENV VIRTUAL_ENV=$VENV_PATH PATH="$VENV_PATH/bin:$PATH"

# Install Astral UV package manager
ADD https://astral.sh/uv/install.sh /install.sh
RUN chmod +x /install.sh && \
    /install.sh && \
    rm /install.sh

# Define the working directory for the application
WORKDIR $APP_PATH

# Install required Python packages using UV
COPY ./requirements.txt .
RUN $UV_PATH venv $VENV_PATH && \
    $UV_PATH pip install --no-cache -r requirements.txt

# TEST STAGE - Build upon the base image
FROM build as test

# Import arguments necessary for the test stage
ARG APP_PATH
ARG UV_PATH

# Install development and testing packages
COPY ./requirements-dev.txt .
RUN $UV_PATH pip install --no-cache -r requirements-dev.txt

# Copy the application and test files
COPY ./app app
COPY ./tests tests
COPY ./pyproject.toml .
ENV PYTHONPATH="$APP_PATH:$PYTHONPATH"

# Define the command to run tests and generate reports
CMD ["pytest", "--junitxml", "coverage/report.xml", "--cov-report", "term", "--cov-report", "xml:coverage/coverage.xml", "--cov=.", "tests"]

# RELEASE IMAGE - Optimized for production with only necessary components
FROM python:3.12-alpine as release

# Import arguments necessary for the release stage
ARG APP_PATH
ARG VENV_PATH

# Copy the virtual environment from the build stage
COPY --from=build $VENV_PATH $VENV_PATH

# Set up the application in the working directory
WORKDIR $APP_PATH
COPY --from=test $APP_PATH/app app
COPY --from=test $APP_PATH/pyproject.toml .

# Activate the virtual environment in the container
ENV PATH="$VENV_PATH/bin:$PATH"
ENV PYTHONPATH="$APP_PATH:$PYTHONPATH"

# Set the entry point for the container
ENTRYPOINT ["python3", "app/main.py"]
