

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-executor

COPY postprocessing-batch /app/postprocessing-batch

ENTRYPOINT ["python", "/app/postprocessing-batch/upload.py"]
