

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-executor

COPY data-retrieval /app/data-retrieval
# TODO: Add promcsv dependency
# TODO: Install procsv dependencies

ENTRYPOINT ["python", "/app/data-retrieval/data-retrieval.py"]
