

FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-executor

COPY download-model /app/download-model

ENTRYPOINT ["python", "/app/download-model/download.py"]
