FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-executor

COPY preprocessing preprocessing
COPY load-data data

RUN pip install -r preprocessing/requirements.txt

ENTRYPOINT ["python"]
