
FROM registry.gitlab.bsc.es/datacentric-computing/cloudskin-project/cloudskin-registry/scanflow-agent

ENV AGENT_NAME planner
ENV AGENT_TYPE planner

RUN mkdir /agent
COPY planner /agent

ENV sensors '{"reactive_watch_qos": {"name": "reactive_watch_qos", "func": "scanflow.agent.template.planner.custom_sensors.reactive_watch_qos", "trigger": {"type": "interval", "weeks": 0, "days": 0, "hours": 0, "minutes": 5, "seconds": 0, "start_date": null, "end_date": null, "timezone": null, "jitter": null}, "kwargs": {"frequency": 300, "app_name": "dlstreamer-pipeline-server", "nearbyone_env_name": "nearbyone.innovationlab", "nearbyone_organization_id": "abcd-1234-uvxyz-9876", "nearbyone_env_email": "fake.username@example.com", "nearbyone_env_password": "fake-password"}}}' 

RUN pip install -r /agent/requirements.txt

ENV PYTHONPATH="$PYTHONPATH:/scanflow/scanflow/scanflow/agent/template/planner"

CMD [ "cp /agent/* /scanflow/scanflow/scanflow/agent/template/planner && uvicorn main:agent --reload --host 0.0.0.0 --port 8080" ]
